version: '3.8'

services :
    be:
      container_name: bedatn
      build:
        context : .
        dockerfile: Dockerfile
      ports:
        - "8080:8080"
      environment:
        SPRING_DATASOURCE_URL: jdbc:mysql://35.221.212.250:3306/quanlynhahang
        SPRING_DATASOURCE_USERNAME: root
        SPRING_DATASOURCE_PASSWORD: 12345
        host.be: "http://bedatn:8080"
        host.fe: "http://fedatn:4200"
      depends_on:
        - fe
    fe:
      container_name: fedatn
      build:
        context: /home/phannhatlong44/DuAnTotNghiepFE
        dockerfile: Dockerfile
      ports:
        - "4200:4200"
